extend setup-checklist: split KKP/kubeone, add baremetal requirements
kubermatic-labs/community-components pull request #10
Opened 2021-01-21 12:49 UTC by toschneck

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
```

2021-01-21 13:12 UTC, chrkl requested changes

2021-01-21 13:12 UTC, chrkl commented on knowledge-base/setup-checklist/kubeone/kubeone-baremetal-requirements.md
> +To set up Kubermatic behind [MetalLB](https://metallb.universe.tf/), we need a few routable, not distributed IP address. This could be sliced into one CIDR. The virtual IPs should be routed to the ta
The phrase "not distributed IP address." might be confusing. I'd rather say "not managed by DHCP" or similar.

2021-01-21 13:12 UTC, chrkl commented on knowledge-base/setup-checklist/kubeone/kubeone-baremetal-requirements.md
> +  - [OpenEBS](https://docs.openebs.io/) (recommended)
I would not keep this as a general recommendation. Make very clear that this holds only for PoC / test environments or remove the mark entirely.

2021-01-21 13:12 UTC, chrkl commented on knowledge-base/setup-checklist/kubeone/README.md
> +* DHCP for worker nodes is recommended
Better write "required" instead of recommended for machine-controller usage.

2021-01-21 13:12 UTC, chrkl commented on knowledge-base/setup-checklist/kubeone/kubeone-baremetal-requirements.md
> +3. List of IP addresses, to provision the target environment
Unclear to me what this means? A list of bare-metal nodes?

2021-02-02 13:23 UTC, toschneck commented
@chrkl please review again :-)

2021-02-02 13:40 UTC, chrkl commented
/approve

2021-02-05 10:11 UTC, merged